[build]
  command = "remix build"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000
  
[[redirects]]
  from = "/media-kit"
  to = "https://app.jeffamzn.com/campaign/f862f1e4-156d-40bf-8e44-23b62463988e/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/rate-card"
  to = "https://app.jeffamzn.com/campaign/f25acf35-9c3e-427b-acf5-fec6c921dee2/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/sample"
  to = "https://app.jeffamzn.com/campaign/9f60dcc3-107c-4075-94a8-cb5c96a36423/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/preview/anthropic"
  to = "https://app.jeffamzn.com/campaign/c3532b3b-c14a-48f7-9e93-f4ccacac445a/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/preview/perplexity"
  to = "https://app.jeffamzn.com/campaign/1566f42a-ce41-4dd2-93f9-a3de5820faaa/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/preview/vanta"
  to = "https://app.jeffamzn.com/campaign/0860355d-3e01-401a-8cb2-1c252af4b18e/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/preview/snowflake"
  to = "https://app.jeffamzn.com/campaign/37470068-f973-4ec9-8c54-1cf632f5b9bf/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/preview/plaid"
  to = "https://app.jeffamzn.com/campaign/c5584ee0-e254-4931-870f-7da46c59282f/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/preview/teads"
  to = "https://app.jeffamzn.com/campaign/5f8dc8ec-c0fc-44f0-9fc2-b84f0302d75f/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true
  
[[redirects]]
  from = "/preview/nebius"
  to = "https://app.jeffamzn.com/campaign/b434f8c2-41df-46c7-9ac1-c92e4d56fb32/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/preview/headway"
  to = "https://app.jeffamzn.com/campaign/0b1f0365-172c-49e2-9c4e-3a741ab576c8/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/preview/blacksky"
  to = "https://app.jeffamzn.com/campaign/31629ed4-c2da-4296-bbf5-bf2ecdf685a3/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/preview/qa-wolf"
  to = "https://app.jeffamzn.com/campaign/36c15cd9-5eb6-4c7c-9fd5-1ba81e6abe74/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/preview/smartasset"
  to = "https://app.jeffamzn.com/campaign/fe1a8617-7985-4086-bb9b-8bef88624e33/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/preview/aeropay"
  to = "https://app.jeffamzn.com/campaign/90e243cd-ca9a-44c9-9799-768e8220da34/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/preview/polymarket"
  to = "https://app.jeffamzn.com/campaign/03a91893-c866-45db-b507-9ee799ebb3a3/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/preview/kalshi"
  to = "https://app.jeffamzn.com/campaign/e142f718-420c-483e-9b4b-585eb334e28b/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/preview/mercedes-benz"
  to = "https://app.jeffamzn.com/campaign/3d0e1311-ed88-4b79-b565-dd37d6f1e509/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/preview/pandadoc"
  to = "https://app.jeffamzn.com/campaign/3b6fe241-842f-4da6-8fe7-7050c9f073d4/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/klarna"
  to = "https://app.jeffamzn.com/campaign/03a9fbb5-d8f4-424a-9160-a2f6239ef058/e0b14610-4448-4657-ae89-21598fe78de2"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
